DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS SKILLS;

CREATE TABLE USER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT UNIQUE NOT NULL,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE SKILLS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT UNIQUE NOT NULL,
  STARS INTEGER NOT NULL,
  DESCRIBE TEXT NOT NULL,
  EDIT_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
