DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS SKILLS;
DROP TABLE IF EXISTS PROJECTS;
DROP TABLE IF EXISTS PLANS;

CREATE TABLE USER (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT UNIQUE NOT NULL,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE SKILLS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT UNIQUE NOT NULL,
  STARS INTEGER NOT NULL,
  DESCRIBE TEXT NOT NULL,
  EDIT_TIME INTEGER DEFAULT NULL
);

CREATE TABLE PROJECTS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT UNIQUE NOT NULL,
  DESCRIBE TEXT NOT NULL,
  EDIT_TIME INTEGER DEFAULT NULL
);

CREATE TABLE PLANS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT UNIQUE NOT NULL,
  TIMESPAN TEXT NOT NULL,
  START_TIME INTEGER DEFAULT NULL,
  END_TIME INTEGER DEFAULT NULL,
  FINISHED INTEGER DEFAULT 0,
  GOAL INTEGER DEFAULT 1
);
